/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type DatabaseName = string;
export type AlertsAvailable = boolean;
export type Id = string;
export type Label = string;
export type Notifier = string;
export type Destinations = DestinationOption[];
export type Id1 = string;
export type Name = string;
export type WatchlistType = string;
export type DestinationId = string;
export type DestinationLabel = string;
export type Enabled = boolean;
export type CommitteeIds = string[];
export type Races = {
  [k: string]: unknown;
}[];
export type Contributors = {
  [k: string]: unknown;
}[];
export type Watchlists = WatchlistData[];
export type WatchlistName = string | null;
export type FilingId = string;
export type MessageText = string | null;
export type SentAt = string | null;
export type RecentAlerts = AlertLogData[];
export type PrefillCommitteeId = string | null;
export type PrefillTemplate = string | null;

export interface AlertsPageData {
  database_name: DatabaseName;
  alerts_available?: AlertsAvailable;
  destinations?: Destinations;
  watchlists?: Watchlists;
  recent_alerts?: RecentAlerts;
  prefill_committee_id?: PrefillCommitteeId;
  prefill_template?: PrefillTemplate;
  [k: string]: unknown;
}
export interface DestinationOption {
  id: Id;
  label: Label;
  notifier: Notifier;
  [k: string]: unknown;
}
export interface WatchlistData {
  id: Id1;
  name: Name;
  watchlist_type: WatchlistType;
  destination_id: DestinationId;
  destination_label?: DestinationLabel;
  enabled?: Enabled;
  committee_ids?: CommitteeIds;
  races?: Races;
  contributors?: Contributors;
  [k: string]: unknown;
}
export interface AlertLogData {
  watchlist_name?: WatchlistName;
  filing_id: FilingId;
  message_text?: MessageText;
  sent_at?: SentAt;
  [k: string]: unknown;
}
