/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type CommitteeId = string;
export type Cycle = number;
export type DatabaseName = string;
export type CommitteeId1 = string;
export type Name = string | null;
export type CommitteeType = string | null;
export type Designation = string | null;
export type CandidateId = string | null;
export type PartyAffiliation = string | null;
export type FilingFrequency = string | null;
export type AddressStreet1 = string | null;
export type AddressStreet2 = string | null;
export type AddressCity = string | null;
export type AddressState = string | null;
export type AddressZip = string | null;
export type TreasurerName = string | null;
export type Cycle1 = number | null;
export type CandidateId1 = string;
export type Name1 = string | null;
export type PartyAffiliation1 = string | null;
export type State = string | null;
export type Office = string | null;
export type District = string | null;
export type IncumbentChallengerStatus = string | null;
export type PrincipalCampaignCommittee = string | null;
export type AddressStreet11 = string | null;
export type AddressStreet21 = string | null;
export type AddressCity1 = string | null;
export type AddressState1 = string | null;
export type AddressZip1 = string | null;
export type Cycle2 = number | null;
export type F3CoverageThroughDate = string | null;
export type F3TotalReceipts = number | null;
export type F3TotalDisbursements = number | null;
export type F3CashOnHandEnd = number | null;
export type FilingId = string;
export type CoverRecordForm = string | null;
export type FilerId = string | null;
export type FilerName = string | null;
export type CoverageFromDate = string | null;
export type CoverageThroughDate = string | null;
export type Filings = Filing[];
export type AlertsAvailable = boolean;
export type Error = string | null;

export interface CommitteePageData {
  committee_id: CommitteeId;
  cycle: Cycle;
  database_name: DatabaseName;
  committee?: Committee | null;
  candidate?: Candidate | null;
  filings?: Filings;
  alerts_available?: AlertsAvailable;
  error?: Error;
  [k: string]: unknown;
}
export interface Committee {
  committee_id: CommitteeId1;
  name?: Name;
  committee_type?: CommitteeType;
  designation?: Designation;
  candidate_id?: CandidateId;
  party_affiliation?: PartyAffiliation;
  filing_frequency?: FilingFrequency;
  address_street1?: AddressStreet1;
  address_street2?: AddressStreet2;
  address_city?: AddressCity;
  address_state?: AddressState;
  address_zip?: AddressZip;
  treasurer_name?: TreasurerName;
  cycle?: Cycle1;
  [k: string]: unknown;
}
export interface Candidate {
  candidate_id: CandidateId1;
  name?: Name1;
  party_affiliation?: PartyAffiliation1;
  state?: State;
  office?: Office;
  district?: District;
  incumbent_challenger_status?: IncumbentChallengerStatus;
  principal_campaign_committee?: PrincipalCampaignCommittee;
  address_street1?: AddressStreet11;
  address_street2?: AddressStreet21;
  address_city?: AddressCity1;
  address_state?: AddressState1;
  address_zip?: AddressZip1;
  cycle?: Cycle2;
  f3_coverage_through_date?: F3CoverageThroughDate;
  f3_total_receipts?: F3TotalReceipts;
  f3_total_disbursements?: F3TotalDisbursements;
  f3_cash_on_hand_end?: F3CashOnHandEnd;
  [k: string]: unknown;
}
export interface Filing {
  filing_id: FilingId;
  cover_record_form?: CoverRecordForm;
  filer_id?: FilerId;
  filer_name?: FilerName;
  coverage_from_date?: CoverageFromDate;
  coverage_through_date?: CoverageThroughDate;
  [k: string]: unknown;
}
