/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type State = string;
export type Office = string;
export type District = string | null;
export type Cycle = number;
export type DatabaseName = string;
export type ContestDescription = string;
export type CandidateId = string;
export type Name = string | null;
export type PartyAffiliation = string | null;
export type State1 = string | null;
export type Office1 = string | null;
export type District1 = string | null;
export type IncumbentChallengerStatus = string | null;
export type PrincipalCampaignCommittee = string | null;
export type AddressStreet1 = string | null;
export type AddressStreet2 = string | null;
export type AddressCity = string | null;
export type AddressState = string | null;
export type AddressZip = string | null;
export type Cycle1 = number | null;
export type F3CoverageThroughDate = string | null;
export type F3TotalReceipts = number | null;
export type F3TotalDisbursements = number | null;
export type F3CashOnHandEnd = number | null;
export type Candidates = Candidate[];
export type Error = string | null;

export interface ContestPageData {
  state: State;
  office: Office;
  district?: District;
  cycle: Cycle;
  database_name: DatabaseName;
  contest_description: ContestDescription;
  candidates?: Candidates;
  error?: Error;
  [k: string]: unknown;
}
export interface Candidate {
  candidate_id: CandidateId;
  name?: Name;
  party_affiliation?: PartyAffiliation;
  state?: State1;
  office?: Office1;
  district?: District1;
  incumbent_challenger_status?: IncumbentChallengerStatus;
  principal_campaign_committee?: PrincipalCampaignCommittee;
  address_street1?: AddressStreet1;
  address_street2?: AddressStreet2;
  address_city?: AddressCity;
  address_state?: AddressState;
  address_zip?: AddressZip;
  cycle?: Cycle1;
  f3_coverage_through_date?: F3CoverageThroughDate;
  f3_total_receipts?: F3TotalReceipts;
  f3_total_disbursements?: F3TotalDisbursements;
  f3_cash_on_hand_end?: F3CashOnHandEnd;
  [k: string]: unknown;
}
