/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type ExportId = number;
export type ExportUuid = string | null;
export type CreatedAt = string | null;
export type Status = string | null;
export type FilingsCount = number;
export type CoverOnly = boolean;
export type ErrorMessage = string | null;
export type Id = number;
export type InputType = string;
export type InputValue = string;
export type Cycle = number | null;
export type FilingIds = string[];
export type Inputs = ExportInputInfo[];
export type FilingId = string;
export type Success = boolean;
export type Message = string | null;
export type CoverRecordForm = string | null;
export type FilerId = string | null;
export type FilerName = string | null;
export type CoverageFromDate = string | null;
export type CoverageThroughDate = string | null;
export type Filings = ExportFilingInfo[];
export type DatabaseName = string;
export type Error = string | null;

export interface ExportPageData {
  export_id: ExportId;
  export_uuid?: ExportUuid;
  created_at?: CreatedAt;
  status?: Status;
  filings_count?: FilingsCount;
  cover_only?: CoverOnly;
  error_message?: ErrorMessage;
  inputs?: Inputs;
  filings?: Filings;
  database_name: DatabaseName;
  error?: Error;
  [k: string]: unknown;
}
export interface ExportInputInfo {
  id: Id;
  input_type: InputType;
  input_value: InputValue;
  cycle?: Cycle;
  filing_ids?: FilingIds;
  [k: string]: unknown;
}
export interface ExportFilingInfo {
  filing_id: FilingId;
  success: Success;
  message?: Message;
  cover_record_form?: CoverRecordForm;
  filer_id?: FilerId;
  filer_name?: FilerName;
  coverage_from_date?: CoverageFromDate;
  coverage_through_date?: CoverageThroughDate;
  [k: string]: unknown;
}
