/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type FilingId = string;
export type FilingId1 = string;
export type CoverRecordForm = string | null;
export type FilerId = string | null;
export type FilerName = string | null;
export type CoverageFromDate = string | null;
export type CoverageThroughDate = string | null;
export type FormData = {
  [k: string]: unknown;
} | null;
export type DatabaseName = string;
export type Error = string | null;

export interface FilingDetailPageData {
  filing_id: FilingId;
  filing?: Filing | null;
  form_data?: FormData;
  database_name: DatabaseName;
  error?: Error;
  [k: string]: unknown;
}
export interface Filing {
  filing_id: FilingId1;
  cover_record_form?: CoverRecordForm;
  filer_id?: FilerId;
  filer_name?: FilerName;
  coverage_from_date?: CoverageFromDate;
  coverage_through_date?: CoverageThroughDate;
  [k: string]: unknown;
}
