/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type DatabaseName = string;
export type CanWrite = boolean;

export interface IndexPageData {
  database_name: DatabaseName;
  can_write?: CanWrite;
  [k: string]: unknown;
}
