export const reportCodeLabels: Record<string, string> = {
  M2: 'February Monthly',
  M3: 'March Monthly',
  M4: 'April Monthly',
  M5: 'May Monthly',
  M6: 'June Monthly',
  M7: 'July Monthly',
  M8: 'August Monthly',
  M9: 'September Monthly',
  M10: 'October Monthly',
  M11: 'November Monthly',
  M12: 'December Monthly',
  Q1: 'April quarterly',
  Q2: 'July quarterly',
  Q3: 'October quarterly',
  MY: 'Mid-year report',
  '12P': 'Pre-Primary',
  '12C': 'Pre-Convention',
  '12G': 'Pre-General',
  '12R': 'Pre-Runoff',
  '12S': 'Pre-Special',
  '30G': 'Post-General',
  '30R': 'Post-Runoff',
  '30S': 'Post-Special',
  '30P': 'Post-Primary',
  '60D': 'Post-Convention',
  '10D': 'Pre-Election (10D)',
  '30D': 'Post-Election (30D)',
  '10G': 'Pre-General (last used: 1982)',
  '10P': 'Pre-Primary (last used: 1982)',
  '10R': 'Pre-Runoff (last used: 1980)',
  '10S': 'Pre-Special (last used: 1980)',
  M7S: 'July Monthly/Semiannual',
  MSA: 'Monthly Semiannual Mid Year',
  MSY: 'Monthly Semiannual Year End',
  MYS: 'Monthly Year End/Semiannual',
  Q2S: 'July Quarterly/Semiannual',
  QSA: 'Quarterly Semiannual (My)',
  QYE: 'Quarterly Semiannual (Ye)',
  QYS: 'Quarterly Year End/Semiannual',
  QMS: 'Quarterly Mid Year/Semiannual',
  TER: 'Termination',
  '24': '24-Hour Report',
  '48': '48-Hour Report',
  '90D': 'Post Inaugural',
  '90S': 'Post Inaugural Supplement',
  CA: 'Comprehensive Amendment',
  ADJ: 'Comprehensive Adjusted Amendment',
  YE: 'Year End',
};

export function getReportLabel(code: string | null | undefined): string {
  if (!code) return 'Unknown';
  return reportCodeLabels[code] ?? code;
}
